version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 99
  assignees:
  - chrismcg
  ignore:
  - dependency-name: earmark
    versions:
    - 1.4.13
  - dependency-name: excoveralls
    versions:
    - 0.13.4
- package-ecosystem: npm
  directory: "/assets"
  schedule:
    interval: monthly
  open-pull-requests-limit: 99
  assignees:
  - chrismcg
  ignore:
  - dependency-name: webpack-cli
    versions:
    - 4.3.1
    - 4.4.0
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.3
    - 1.3.5
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: sass-loader
    versions:
    - 10.1.0
  - dependency-name: css-loader
    versions:
    - 5.0.1
